from models.base import db 
from models.legajos.legajo import Legajo
from models.clientes.cliente import Cliente
from models.muestras.muestra import Muestra
from models.mails.mail import Mail
from models.presupuestos.presupuesto import Presupuesto
from models.presupuestos.STAN import STAN
from models.presupuestos.presupuesto_stan import PresupuestoStan
from models.presupuestos.ensayo import Ensayo
from models.presupuestos.ensayo_stan import EnsayoStan
from models.documentos.documento import Documento
from models.resultados_encuestas.resultado_encuesta import ResultadoEncuesta
from models.presupuestos.mediodepago import MedioPago
from models.personal.area import Area
from models.patrimonio.bien import Bien
from models.archivos_admin.archivo import Archivo
from models.archivos_admin.carpeta import Carpeta
from models.personal.empleado import Empleado   
from models.personal.personal import User
from models.personal.ausencia import Ausencia
from models.empleado_distribucion.empleado_distribucion import Empleado_Distribucion